In [1]:
import os
import pandas as pd

In [2]:
file_path = os.path.join('..', 'data', 'raw', 'Airbnb_Open_Data.csv')

In [3]:
df = pd.read_csv(file_path, low_memory=False)

In [4]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [5]:
print(f'Dataset Dimensions: {df.shape[0]:,} rows and {df.shape[1]} columns')

Dataset Dimensions: 102,599 rows and 26 columns

In [6]:
print(f'Data Technical Breakdown: {df.info()}')

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB
Data Technical Breakdown: None

In [7]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [8]:
total_duplicates = df.duplicated(subset=['id']).sum()

In [9]:
print(f'Total Duplicates: {total_duplicates:,} rows')

Total Duplicates: 541 rows

In [10]:
rows_before = df.shape[0]
df.drop_duplicates(subset=['id'], inplace=True)
rows_after = df.shape[0]

In [11]:
print(f'No. of rows before dropping duplicates: {rows_before:,}')
print(f'No. of rows after dropping duplicates: {rows_after:,}')

No. of rows before dropping duplicates: 102,599
No. of rows after dropping duplicates: 102,058

In [12]:
null_counts = df.isnull().sum()
null_percentage = (null_counts / len(df)) * 100

In [13]:
missing_df = pd.DataFrame({'Missing Counts': null_counts, 'Missing Percentage': null_percentage})

In [14]:
missing_df[missing_df['Missing Counts'] > 0].sort_values(by='Missing Counts', ascending=False)

                                Missing Counts  Missing Percentage
license                                 102056           99.998040
house_rules                              51842           50.796606
last review                              15832           15.512748
reviews per month                        15818           15.499030
country                                    532            0.521272
availability 365                           448            0.438966
host name                                  404            0.395853
minimum nights                             400            0.391934
review rate number                         319            0.312567
calculated host listings count             319            0.312567
host_identity_verified                     289            0.283172
service fee                                273            0.267495
NAME                                       250            0.244959
price                                      247            0.242019
Construction year                          214            0.209685
number of reviews                          183            0.179310
country code                               131            0.128358
instant_bookable                           105            0.102883
cancellation_policy                         76            0.074467
neighbourhood group                         29            0.028415
neighbourhood                               16            0.015677
long                                         8            0.007839
lat                                          8            0.007839

In [15]:
#license column has 99% missing values, so we can drop it
df.drop(columns=['license'], inplace=True)

In [16]:
df['house_rules'] = df['house_rules'].fillna('No rules specified')

In [17]:

missing_reviews_context = df[df['reviews per month'].isnull()]['number of reviews'].value_counts()
print(missing_reviews_context)

number of reviews
0.0      15673
80.0         2
2.0          2
309.0        1
14.0         1
4.0          1
294.0        1
129.0        1
82.0         1
193.0        1
147.0        1
177.0        1
185.0        1
62.0         1
66.0         1
65.0         1
17.0         1
145.0        1
26.0         1
6.0          1
11.0         1
Name: count, dtype: int64

In [18]:
median_review_rate = df['reviews per month'].median()

In [19]:
df.loc[(df['reviews per month'].isnull()) & (df['number of reviews'] == 0), 'reviews per month'] = 0.0

In [20]:
df.loc[(df['reviews per month'].isnull()) & (df['number of reviews'] > 0), 'reviews per month'] = median_review_rate

In [21]:
# Filled reviews per month with 0 for listings with no reviews and median for listings with reviews but missing review rate
missing_reviews_context = df[df['reviews per month'].isnull()]['number of reviews'].value_counts()
print(missing_reviews_context)

Series([], Name: count, dtype: int64)

In [22]:
# Fill missing values in the 'country' column with 'United States'
df['country'] = df['country'].fillna('United States')

In [23]:
df['country code'].isnull().sum()

np.int64(131)

In [24]:
# Fill missing values in the 'country code' column with 'US'
df['country code'] = df['country code'].fillna('US')

In [25]:
df['neighbourhood group'].unique()

<StringArray>
[     'Brooklyn',     'Manhattan',       'brookln',      'manhatan',
        'Queens',             nan, 'Staten Island',         'Bronx']
Length: 8, dtype: str

In [26]:
df['neighbourhood group'] = df['neighbourhood group'].str.strip().str.title()

In [27]:
neighbourhood_group_mapping = {
    'Brookln': 'Brooklyn',
    'Manhatan': 'Manhattan'}

In [28]:
#Cleaned the neighbourhood group column by stripping whitespace, converting to title case, and replacing misspelled values with correct ones
df['neighbourhood group'] = df['neighbourhood group'].replace(neighbourhood_group_mapping)

In [29]:
df['neighbourhood group'].unique()

<StringArray>
['Brooklyn', 'Manhattan', 'Queens', nan, 'Staten Island', 'Bronx']
Length: 6, dtype: str

In [30]:
df.dtypes

id                                  int64
NAME                                  str
host id                             int64
host_identity_verified                str
host name                             str
neighbourhood group                   str
neighbourhood                         str
lat                               float64
long                              float64
country                               str
country code                          str
instant_bookable                   object
cancellation_policy                   str
room type                             str
Construction year                 float64
price                                 str
service fee                           str
minimum nights                    float64
number of reviews                 float64
last review                           str
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                           str
dtype: object

In [31]:
df['price'] = df['price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False)

In [32]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [33]:
df['service fee'].str.contains('$').sum()

np.int64(101785)

In [34]:
df['service fee'] = df['service fee'].str.replace('$', '', regex=False)

In [35]:
df['service fee'] = pd.to_numeric(df['service fee'], errors='coerce')

In [36]:
df.dtypes

id                                  int64
NAME                                  str
host id                             int64
host_identity_verified                str
host name                             str
neighbourhood group                   str
neighbourhood                         str
lat                               float64
long                              float64
country                               str
country code                          str
instant_bookable                   object
cancellation_policy                   str
room type                             str
Construction year                 float64
price                             float64
service fee                       float64
minimum nights                    float64
number of reviews                 float64
last review                           str
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                           str
dtype: object

In [37]:
df.loc[(df['price'].isnull()) & (df['service fee'].isnull()), ['price', 'service fee']]

        price  service fee
13595     NaN          NaN
13596     NaN          NaN
13597     NaN          NaN
13598     NaN          NaN
13599     NaN          NaN
13600     NaN          NaN
13601     NaN          NaN
37169     NaN          NaN
37170     NaN          NaN
37171     NaN          NaN
37172     NaN          NaN
37173     NaN          NaN
37174     NaN          NaN
37175     NaN          NaN
37176     NaN          NaN
37263     NaN          NaN
37264     NaN          NaN
37265     NaN          NaN
37266     NaN          NaN
37267     NaN          NaN
37268     NaN          NaN
37269     NaN          NaN
37270     NaN          NaN
79785     NaN          NaN
79786     NaN          NaN
79787     NaN          NaN
79788     NaN          NaN
79789     NaN          NaN
102045    NaN          NaN
102046    NaN          NaN
102047    NaN          NaN
102048    NaN          NaN
102049    NaN          NaN
102050    NaN          NaN

In [38]:
complete_financials = df[df['price'].notnull() & df['service fee'].notnull() & (df['price'] > 0)]

fee_ratios = complete_financials['service fee'] / complete_financials['price']

print(fee_ratios.value_counts().head())

0.200000    20419
0.199029      247
0.199588      228
0.199507      223
0.199584      218
Name: count, dtype: int64

In [39]:
df.loc[(df['price'].isnull()) & (df['service fee'].notnull()), ['price']] = df['service fee']*5

In [40]:
df['price'].isnull().sum()

np.int64(34)

In [41]:
df = df.dropna(subset=['price', 'service fee'], how='all')

In [42]:
df['price'].isnull().sum()

np.int64(0)

In [49]:
negative_count = (df['minimum nights'] < 0).sum()

In [50]:
print(f"Number of rows with negative minimum nights: {negative_count}")

Number of rows with negative minimum nights: 13

In [51]:
df.loc[df['minimum nights'] < 0, 'minimum nights'] = 1

In [52]:
df['minimum nights'].min()

np.float64(1.0)

In [57]:
df['minimum nights'].nlargest(10)

42398    5645.0
350      3455.0
42407    2645.0
5768     1250.0
2855     1000.0
71031    1000.0
13405     999.0
26342     999.0
38665     999.0
83506     999.0
Name: minimum nights, dtype: float64

In [55]:
(df['minimum nights'] > 365).sum()

np.int64(35)

In [58]:
df.loc[df['minimum nights'] > 365, 'minimum nights'] = 365

In [59]:
print("---  FINAL DATASET HEALTH PROFILE ---")
print(f"Total Rows: {df.shape[0]:,}")
print(f"Total Columns: {df.shape[1]}")
print("\n---  DATA TYPES & NULL COUNTS ---")
print(df.info())

print("\n---  FINANCIAL SUMMARY SANITY CHECK ---")
print(df[['price', 'service fee', 'reviews per month']].describe().round(2))

---  FINAL DATASET HEALTH PROFILE ---
Total Rows: 102,024
Total Columns: 25

---  DATA TYPES & NULL COUNTS ---
<class 'pandas.DataFrame'>
Index: 102024 entries, 0 to 102057
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102024 non-null  int64
 1   NAME                            101774 non-null  str
 2   host id                         102024 non-null  int64
 3   host_identity_verified          101735 non-null  str
 4   host name                       101625 non-null  str
 5   neighbourhood group             101995 non-null  str
 6   neighbourhood                   102008 non-null  str
 7   lat                             102016 non-null  float64
 8   long                            102016 non-null  float64
 9   country                         102024 non-null  str
 10  country code                    102024 non-null  str
 11  instant_bookable                101919 non-null  object
 12  cancellation_policy             101948 non-null  str
 13  room type                       102024 non-null  str
 14  Construction year               101810 non-null  float64
 15  price                           102024 non-null  float64
 16  service fee                     101785 non-null  float64
 17  minimum nights                  101624 non-null  float64
 18  number of reviews               101841 non-null  float64
 19  last review                     86200 non-null   str
 20  reviews per month               101901 non-null  float64
 21  review rate number              101705 non-null  float64
 22  calculated host listings count  101705 non-null  float64
 23  availability 365                101576 non-null  float64
 24  house_rules                     102024 non-null  str
dtypes: float64(11), int64(2), object(1), str(11)
memory usage: 20.2+ MB
None

---  FINANCIAL SUMMARY SANITY CHECK ---
           price  service fee  reviews per month
count  102024.00    101785.00          101901.00
mean      625.30       125.04               1.16
std       331.63        66.33               1.68
min        50.00        10.00               0.00
25%       340.00        68.00               0.09
50%       624.00       125.00               0.48
75%       913.00       183.00               1.71
max      1200.00       240.00              90.00

In [45]:
df.info()

<class 'pandas.DataFrame'>
Index: 102024 entries, 0 to 102057
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102024 non-null  int64
 1   NAME                            101774 non-null  str
 2   host id                         102024 non-null  int64
 3   host_identity_verified          101735 non-null  str
 4   host name                       101625 non-null  str
 5   neighbourhood group             101995 non-null  str
 6   neighbourhood                   102008 non-null  str
 7   lat                             102016 non-null  float64
 8   long                            102016 non-null  float64
 9   country                         102024 non-null  str
 10  country code                    102024 non-null  str
 11  instant_bookable                101919 non-null  object
 12  cancellation_policy             101948 non-null  str
 13  room type                       102024 non-null  str
 14  Construction year               101810 non-null  float64
 15  price                           102024 non-null  float64
 16  service fee                     101785 non-null  float64
 17  minimum nights                  101624 non-null  float64
 18  number of reviews               101841 non-null  float64
 19  last review                     86200 non-null   str
 20  reviews per month               101901 non-null  float64
 21  review rate number              101705 non-null  float64
 22  calculated host listings count  101705 non-null  float64
 23  availability 365                101576 non-null  float64
 24  house_rules                     102024 non-null  str
dtypes: float64(11), int64(2), object(1), str(11)
memory usage: 20.2+ MB

In [60]:
output_dir = os.path.join('..', 'data', 'processed')
output_file = os.path.join(output_dir, 'nyc_airbnb_cleaned.csv')

In [61]:
os.makedirs(output_dir, exist_ok=True)

In [62]:
df.to_csv(output_file, index=False)

In [63]:
df.describe()

,id,host id,lat,long,Construction year,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.020240e+05,1.020240e+05,102016.000000,102016.000000,101810.000000,102024.000000,101785.000000,101624.000000,101841.000000,101901.000000,101705.000000,101705.000000,101576.000000
mean,2.918456e+07,4.926429e+10,40.728098,-73.949655,2012.488007,625.297695,125.039249,7.967429,27.519958,1.163871,3.278806,7.936453,141.034634
std,1.627144e+07,2.853564e+10,0.055853,0.049503,5.765854,331.633685,66.325905,18.304749,49.575781,1.682778,1.285038,32.270326,135.422993
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,50.000000,10.000000,1.000000,0.000000,0.000000,1.000000,1.000000,-10.000000
25%,1.509203e+07,2.459659e+10,40.688730,-73.982580,2007.000000,340.000000,68.000000,2.000000,1.000000,0.090000,2.000000,1.000000,3.000000
50%,2.918769e+07,4.912678e+10,40.722290,-73.954445,2012.000000,624.000000,125.000000,3.000000,7.000000,0.480000,3.000000,1.000000,96.000000
75%,4.327452e+07,7.399819e+10,40.762760,-73.932350,2017.000000,913.000000,183.000000,5.000000,31.000000,1.710000,4.000000,2.000000,268.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,1200.000000,240.000000,365.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000